{
 "title": "kBLOCKs Summary",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "🧱 Lifetime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "safestats_pool_lifetime" }
   ]
  },
  {
   "title": "Pool Performance",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_Forge_forged_int{alias=\"core\"} / cardano_node_metrics_Forge_node_is_leader_int{alias=\"core\"} * 100)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Blocks Minted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int"
    }
   ]
  },
  {
   "title": "Blocks Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "safestats_pool_blocks_epoch" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "safestats_pool_live_stake/1000000",
     "legendFormat": "Live Stake"
    },
    {
     "expr": "safestats_pool_active_stake/1000000",
     "legendFormat": "Active Stake"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "safestats_pool_delegator_count", "legendFormat": "Delegators" }
   ]
  },
  {
   "title": "CPU% All Nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance))*100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Memory All Nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Blocks Assigned",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_node_is_leader_int"
    }
   ]
  },
  {
   "title": "Blocks Expected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "safestats_pool_blocks_epoch_estimate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_Forge_metrics_remainingKESPeriods_int * 1.5",
     "legendFormat": "KES Expiry in Days"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 2, "x": 0, "y": 6 }, "options": { "content": "## Core" } },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{alias=\"core\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"core\"} / (node_memory_MemTotal_bytes{alias=\"core\"})))* 100",
     "legendFormat": "Memory"
    },
    {
     "expr": "(node_filesystem_size_bytes{alias=\"core\",fstype=~\"ext.*|xfs\"}-node_filesystem_free_bytes{alias=\"core\",fstype=~\"ext.*|xfs\"})*100 /(node_filesystem_avail_bytes {alias=\"core\",fstype=~\"ext.*|xfs\"}+(node_filesystem_size_bytes{alias=\"core\",fstype=~\"ext.*|xfs\"}-node_filesystem_free_bytes{alias=\"core\",fstype=~\"ext.*|xfs\"}))",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_epoch_int{alias=\"core\"}",
     "legendFormat": "Epoch"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_slotInEpoch_int{alias=\"core\"}",
     "legendFormat": "Slot in Epoch"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_slotNum_int{alias=\"core\"}",
     "legendFormat": "Slot No"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "description": "Connected peers to/from Core Node",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_BlockFetchDecision_peers_connectedPeers_int{alias=\"core\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Txs processed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"core\"}",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Core node uptime",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Time Synchronization (Core)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{alias=\"core\"}",
     "legendFormat": "Est. error(s)"
    },
    {
     "expr": "node_timex_offset_seconds{alias=\"core\"}",
     "legendFormat": "Offset: Node vs. Ref."
    },
    {
     "expr": "node_timex_maxerror_seconds{alias=\"core\"}",
     "legendFormat": "Max. Error (s)"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 }, "options": { "content": "## Relay 1" } },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{alias=\"relay0\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"relay0\"} / (node_memory_MemTotal_bytes{alias=\"relay0\"})))* 100",
     "legendFormat": "Memory"
    },
    {
     "expr": "(node_filesystem_size_bytes{alias=\"relay0\",fstype=~\"ext.*|xfs\"}-node_filesystem_free_bytes{alias=\"relay0\",fstype=~\"ext.*|xfs\"})*100 /(node_filesystem_avail_bytes {alias=\"relay0\",fstype=~\"ext.*|xfs\"}+(node_filesystem_size_bytes{alias=\"relay0\",fstype=~\"ext.*|xfs\"}-node_filesystem_free_bytes{alias=\"relay0\",fstype=~\"ext.*|xfs\"}))",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_epoch_int{alias=\"relay0\"}",
     "legendFormat": "Epoch"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_slotInEpoch_int{alias=\"relay0\"}",
     "legendFormat": "Slot in Epoch"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_slotNum_int{alias=\"relay0\"}",
     "legendFormat": "Slot No"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "description": "Connected peers to/from Relay 1",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_BlockFetchDecision_peers_connectedPeers_int{alias=\"relay0\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Txs processed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"relay0\"}",
     "legendFormat": "Relay1"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Core node uptime",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{alias=\"core\"})",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 2, "x": 0, "y": 10 }, "options": { "content": "## Relay 2" } },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{alias=\"relay1\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"relay1\"} / (node_memory_MemTotal_bytes{alias=\"relay1\"})))* 100",
     "legendFormat": "Memory"
    },
    {
     "expr": "(node_filesystem_size_bytes{alias=\"relay1\",fstype=~\"ext.*|xfs\"}-node_filesystem_free_bytes{alias=\"relay1\",fstype=~\"ext.*|xfs\"})*100 /(node_filesystem_avail_bytes {alias=\"relay1\",fstype=~\"ext.*|xfs\"}+(node_filesystem_size_bytes{alias=\"relay1\",fstype=~\"ext.*|xfs\"}-node_filesystem_free_bytes{alias=\"relay1\",fstype=~\"ext.*|xfs\"}))",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_epoch_int{alias=\"relay1\"}",
     "legendFormat": "Epoch"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_slotInEpoch_int{alias=\"relay1\"}",
     "legendFormat": "Slot in Epoch"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_slotNum_int{alias=\"relay1\"}",
     "legendFormat": "Slot No"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "description": "Connected peers to/from Relay 1",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_BlockFetchDecision_peers_connectedPeers_int{alias=\"relay1\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Txs processed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"relay1\"}",
     "legendFormat": "Relay1"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Core node uptime",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "graph",
   "description": "Sockets_used - Sockets currently in use\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_alloc - Allocated sockets\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nRetransSegs - TCP retransmission packets\n\nOutSegs - Number of packets sent by TCP\n\nInSegs - Number of packets received by TCP",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_netstat_Tcp_CurrEstab{}", "legendFormat": "{{alias}} CurrEstab" },
    { "expr": "node_sockstat_TCP_tw{}", "legendFormat": "{{alias}} TCP_tw" },
    {
     "expr": "node_sockstat_sockets_used{instance=~'$node'}",
     "legendFormat": "{{alias}} Sockets_used"
    },
    { "expr": "node_sockstat_UDP_inuse{}", "legendFormat": "{{alias}} UDP_inuse" },
    { "expr": "node_sockstat_TCP_alloc{}", "legendFormat": "{{alias}} TCP_alloc" },
    {
     "expr": "irate(node_netstat_Tcp_InSegs{instance=~'$node'}[5m])",
     "legendFormat": "{{alias}} Tcp_InSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{}[5m])",
     "legendFormat": "{{alias}} Tcp_OutSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{}[5m])",
     "legendFormat": "{{alias}} Tcp_RetransSegs"
    }
   ]
  },
  {
   "title": "Mempool (bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_mempoolBytes_int{}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Mempool (Txs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int{}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Open  File Descriptor(left)/Context switches(right)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "used filefd" }
   ],
   "targets": [
    { "expr": "node_filefd_allocated{}", "legendFormat": "{{alias}} used filefd" },
    {
     "expr": "irate(node_context_switches_total{}[5m])",
     "legendFormat": "{{alias}} switches"
    }
   ]
  },
  {
   "title": "Internet traffic per hour",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{}[60m])",
     "legendFormat": "{{alias}}_receive"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{}[60m])",
     "legendFormat": "{{alias}}_transmit"
    }
   ]
  },
  {
   "title": "Block sync speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate (cardano_node_ChainDB_metrics_blockNum_int[150s]) *60",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}